### ISSUE TITLE
Git Basics screencasts

### ISSUE THREAD

**Issue by ZhuChara2004** [MastersAcademy/Programming-Basics#330]
Записав серію скрінкастів по роботі з гітом: 
[GitHub](https://github.com/ZhuChara2004/Git-Basics)
[YouTube](https://www.youtube.com/watch?v=P1emCuYA6TA&feature=youtu.be&list=PLhxmTjLwFYTvYutCSEpi-zizIY2rTsD4s)

**Comment by zender991** [comment]
Gitignore generator feature is not obvious.
Need to install additional plugin for it. Also, if you can, will be good to add videos with Pycharm customization (install plugins, add tools, string transfer etc.)
