### ISSUE TITLE
Формат скрінкастів

### ISSUE THREAD

**Issue by ZhuChara2004** [MastersAcademy/Programming-Basics#435]
Скрінкаст другої сесії записаний у новому форматі. Ткніть палець вгору, якщо вам більше сподобався перший і палець вниз, якщо другий. Надалі буду записувати у тому формат, який набере більше лайків. Не треба нічого писати про звук. Питання про формат.

Перший:
[![Session 01 - Python Basics ](https://img.youtube.com/vi/kkW-RQTiGsk/0.jpg)](https://www.youtube.com/watch?v=kkW-RQTiGsk)

Другий:
[![Session 02 - Collections ](https://img.youtube.com/vi/12iKXbV1UXs/0.jpg)](https://www.youtube.com/watch?v=12iKXbV1UXs)

**Comment by Vasyl-Shche** [comment]
В другому майже нічого не чутно...

**Comment by BohdanKostevych** [comment]
Так у другому гірше звук
